// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQ3__U6gvFSQOVgqDICoUN0ncvmfip1g',
    appId: '1:242200995372:web:8c168bfa9a39d57fd15389',
    messagingSenderId: '242200995372',
    projectId: 'quizmaster-e010f',
    authDomain: 'quizmaster-e010f.firebaseapp.com',
    storageBucket: 'quizmaster-e010f.firebasestorage.app',
    measurementId: 'G-CCN2CWR8K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7v5XA1uqTAp_Ngf9Oa74qN0WJJ2QwOPo',
    appId: '1:242200995372:android:4293850985c423d6d15389',
    messagingSenderId: '242200995372',
    projectId: 'quizmaster-e010f',
    storageBucket: 'quizmaster-e010f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEM01FrDa9yThA08PzPIMYYb6VrTxUupQ',
    appId: '1:242200995372:ios:96708d81927cb864d15389',
    messagingSenderId: '242200995372',
    projectId: 'quizmaster-e010f',
    storageBucket: 'quizmaster-e010f.firebasestorage.app',
    androidClientId: '242200995372-jiagu2mvpftrm1iei79nuufgkt0muehl.apps.googleusercontent.com',
    iosClientId: '242200995372-u9610amh2qjs7i0i5rps3ehsh5ggdhre.apps.googleusercontent.com',
    iosBundleId: 'com.quizmaster.quizmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEM01FrDa9yThA08PzPIMYYb6VrTxUupQ',
    appId: '1:242200995372:ios:96708d81927cb864d15389',
    messagingSenderId: '242200995372',
    projectId: 'quizmaster-e010f',
    storageBucket: 'quizmaster-e010f.firebasestorage.app',
    androidClientId: '242200995372-jiagu2mvpftrm1iei79nuufgkt0muehl.apps.googleusercontent.com',
    iosClientId: '242200995372-u9610amh2qjs7i0i5rps3ehsh5ggdhre.apps.googleusercontent.com',
    iosBundleId: 'com.quizmaster.quizmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRQ3__U6gvFSQOVgqDICoUN0ncvmfip1g',
    appId: '1:242200995372:web:819e4d54a24153b0d15389',
    messagingSenderId: '242200995372',
    projectId: 'quizmaster-e010f',
    authDomain: 'quizmaster-e010f.firebaseapp.com',
    storageBucket: 'quizmaster-e010f.firebasestorage.app',
    measurementId: 'G-1JLMM1HH2L',
  );

}